from enum import Enum, auto
class Disability(Enum):
    NO_DISABILITY = 1
    HEARING_IMPAIRMENT = 2
    VISUAL_IMPAIRMENT = 3
    SPEECH_IMPAIRMENT = 4
    MOBILE_IMPAIRMENT = 5
    PHYSICAL_COORD_PROBLEMS = 6
    REDUCED_PHYSICAL_CAPACITY = 7
    SERVERE_DISFIGUREMENT = 8
    LEARNING_DIFFICULTIES = 9
    MENTAL_ILL_HEALTH = 10
    PROGRESSIVE_CONDITIONS = 11
    OTHER_HEALTH = 12
    PREFER_NOT_TO_SAY = 13