from enum import Enum, auto
class JobBreadWinner(Enum):
    CLERICAL_AND_INTERMEDIATE = 1 
    MIDDLE_OR_JUNIOR_MANGERS = 2
    MODERN_PROFESSIONAL_OCCUPATIONS = 3
    ROUTINE_MANUAL_OR_SERVICE_APPLICATIONS = 4
    SEMIROUTINE_MANUAL_OR_SERVICE_APPLICATIONS = 5
    SENIOR_MANAGERS_OR_ADMINISTRATORS = 6
    TECHNICAL_OR_CRAFT_OPERATIONS = 7
    TRADITIONAL_PROFESSIONAL_OCCUPATIONS = 8 
    LONGTERM_JOBSEEKERS_ALLOWANCE = 9 
    DOESNT_APPLY = 10
    PREFER_NOT_TO_SAY = 11